ReferenceError: self is not defined  in SSR (serverside rendering) with nuxtjs for example
in the context of nodejs in serverside the is no "document" in self. self is mocked under "globals". To make your library work with SSR on the server-side, just add this one missing line to create the missing "self"-variable with the correct pointer.